### PR TITLE
Support VS2017

### PR DESCRIPTION
**Pull request by airbreather**
This is part 1 for my proposal to officially resolve [#110 in NTS](https://github.com/NetTopologySuite/NetTopologySuite/issues/110), in a way that should hopefully result in fewer "overhauls" in the future, or if nothing else, limiting how many future changes will have to touch the C# files.  Part 2 will be in the NTS project itself.

The VS2017 style of project offers several advantages over the VS2015 style stuff as well as the older-style csproj files:

1. Since this isn't using the "preview" tooling, I anticipate that there is less risk in losing all the work that was spent in making those `project.json` files which will not work with later versions of Visual Studio.
2. All of the project configuration stuff is in a single file (the *.csproj file).  Not just descriptions for how to build it, but also packages being referenced.
3. The VS2017 NuGet stuff uses a system-wide cache for packages instead of possibly having multiple copies of common packages in each solution's `packages` folder.
4. No longer need to enumerate all the included files in the project file (an advantage shared with `project.json`).
5. Building for all target platforms at once in Visual Studio is much better supported (an advantage shared with `project.json`), and so errors like [#169 in NTS](https://github.com/NetTopologySuite/NetTopologySuite/issues/169) are much less likely to accidentally introduce because the project(s) will simply fail to build.

In addition to the mostly straightforward VS2015-to-VS2017 changes, there are also a few more changes:
1. Building the .NET 3.5 Compact Framework target at the same time as everything else.
    1. Perhaps one disadvantage to this is that in order to build the solution, one must now have the reference assemblies for a probably-not-too-common target platform.  It should be easy enough for someone to just turn off, though, in case it gets too annoying.
2. Using more targeted conditional compilation.  C# code now guards its checks with `#if SOME_FEATURE`, rather than `#if SOME_PLATFORM`.  This lets us put the supported features by platform into the csproj file, and then it avoids the need for some [head-scratchers](https://github.com/NetTopologySuite/GeoAPI/blob/c4742d0ea9a539f10d15e579f1967464322e1766/GeoAPI/GeometryServiceProvider.cs#L79).
    1. Along the way of doing this, I corrected at least [one nit](https://github.com/airbreather/GeoAPI/blob/c4742d0ea9a539f10d15e579f1967464322e1766/GeoAPI/CoordinateSystems/AxisInfo.cs#L64-L95) which would make too many targets use the "fallback" logic instead of [something](https://github.com/airbreather/GeoAPI/blob/e4fec6afde317ad64af3dcccb0d99bb37ee55aa1/GeoAPI/CoordinateSystems/AxisInfo.cs#L64-L99) that's available on those targets.  I thought there were more than that, but maybe I'm thinking more about NTS.
    2. Because of this, I just went ahead and took out a bunch of unused methods from `ValueParser.cs`.  It's internal anyway.
3. Warning 1591 is disabled globally instead of strictly the places that violate it today.  I can easily roll this back if that's not desired; just let me know.
    1. It may be more appropriate to just fix all of the violations, though.
4. We don't need a separate `netstandard1.1` target.  As far as we're concerned, `netstandard1.1` is a proper superset of `netstandard1.0`, and we're not using anything in `netstandard1.1` that's not in `netstandard1.0`.
    1. Furthermore, I could not find any APIs added in a later version of .NET Standard, with the exception of one or two reflection-related ones that are expected to be added in `netstandard2.0`, but 2.0 is still officially marked as a "work in progress".
5. Similarly, we don't really need a separate target for PCL `Profile259`, since it's [equivalent](https://github.com/dotnet/standard/blob/16676bd6bf82f6c899d63dc8847a403f673b20ba/docs/versions.md#mapping-pcl-profiles-to-net-standard) to `netstandard1.0`.
6. Also added a target for PCL `Profile336`.  [Here's](https://github.com/airbreather/GeoAPI/blob/17802818d2cb6976ab28b5e172a5862e71031ac8/GeoAPI/GeoAPI.csproj#L77-L81) the explanation why.  It applies to NTS more than GeoAPI (there's some XLINQ stuff that NTS does conditionally), but it looks like NTS for `Profile336` can't reference GeoAPI for `Profile328`.

I haven't really touched the TeamCity / Travis stuff, nor the batch scripts.  I don't know what you do with them, and I have no clear way of testing it.

I can squash all of these commits and get a much better unified commit message before a final merge, if that does wind up happening.  I wanted to leave it as-is for now.

### CODE REVIEW

**Comment by DGuidi** [comment]
Travis CI has problems building net35-cf stuff...
For the rest, +1 for me

**Comment by FObermaier** [comment]
@airbreather: Thanks again for your valuable effort.
>I can squash all of these commits and get a much better unified commit message before a final merge, if that does wind up happening.

I personally have no objections to merge the pull request as is, I think we don't need to generate more work just for the sake of better commit messages. If you don't feel comfortable with them, well...

@DGuidi We can attempt to fix the Travis build after the merge.

**Comment by DGuidi** [comment]
@FObermaier feel free to integrate, and thanks.
@airbreather thanks for this

**Comment by xivk** [comment]
Great work +1 on merging this!

**Comment by airbreather** [comment]
Added one small commit to skip building our own ICloneable in cases where we don't actually use it... this was handled by `project.json` before my change.

**Pull request merged**
