### PR TITLE
Added Windows CE compatibility and TeamCity independency

### PR DESCRIPTION
**Pull request by ghost**
This pull request has the following changes:
- New project for Windows CE (.NET 3.5 Compact Framework).
- Changes to allow building for all targets from batch script instead to rely only on TeamCity.
- Changes to allow creating NuGet package from batch script instead to rely only on TeamCity.
- Changes to include net35-cf and netstandard1.6 targets into NuGet package.

### CODE REVIEW

**Comment by skarllot** [comment]
Generated NuGet packages

[Release.zip](https://github.com/NetTopologySuite/GeoAPI/files/556683/Release.zip)

**Comment by DGuidi** [comment]
Actually, I'm against introducing support for WinCE platform, that (I think) is a legacy platform.

**Comment by FObermaier** [comment]
A few questions:
* Do the msbuild scripts still work, or did you change everything to use the vbs-script?
* Why did you increase the GeoAPI version, did you/we add functionality or is it just the additional platform?

I'm not against introducing the WinCE platform. Net20 is legacy, too. I'd like to change the NetCore project to rely on NetStandard1.0 instead of 1.6, but we can change that afterwards.

**Comment by skarllot** [comment]
* The msbuild script does not depend of vbscript, the NuGet script do. This can be changed, the vbscript is used to read assembly version to use on NuGet package version. 
* I'm increased the version just because the new platform, the API is exactly the same. 
* I can run some tests on NetStandard1.0 to check whether need changes to run.

**Comment by xivk** [comment]
Can we merge this @FObermaier ? Any changes that need doing before?

**Comment by xivk** [comment]
Do we have to remove the windows CE stuff then?

**Comment by FObermaier** [comment]
IMHO we can merge this, but before releasing I'd like to have the Net.Standard version set as low as possible, Increasing the version number is not indicated when adding a build target. The package version must increase though.

**Comment by skarllot** [comment]
@FObermaier AFAIK different Guids allows to register the all libraries from each framework target at same time.

**Comment by FObermaier** [comment]
According to [this SO post](http://stackoverflow.com/questions/2346620/assemblyinfo-cs-is-there-any-point-in-specifying-a-guid-when-using-comvisiblef) we don't need the `GUID` at all. 
I havn't seen projects that deal with the GUID in such a way.

**Pull request merged**
