### PR TITLE
A pull request to fix travis builds

### PR DESCRIPTION
**Pull request by xivk**
A pull request to fix travis builds, working here until fixed.

### CODE REVIEW

**Comment by xivk** [comment]
This commit broke the build and I can't figure out why:

https://github.com/NetTopologySuite/GeoAPI/commit/3c28b520354577266ca84e6aeecd0e5a98477655

Ping @skarllot

**Comment by FObermaier** [comment]
Maybe it doesn't have anything to do with the previous pull request but with the dotnet version used to compile the thing. 
I have restarted the initial pull-request (https://travis-ci.org/NetTopologySuite/GeoAPI/builds/171170145) and it fails now, too. I swear by all that has any value to me, it did not when I merged it.

**Comment by FObermaier** [comment]
My previous assumption has been proven right:
https://travis-ci.org/NetTopologySuite/GeoAPI/builds/195104520

**Comment by xivk** [comment]
Awesome, thanks! 👍

**Pull request closed without merging**
