### PR TITLE
Added NETCore project.

### PR DESCRIPTION
**Pull request by DGuidi**
see #13 as a reference

### CODE REVIEW

**Comment by xivk** [comment]
Are the builds fixed? I'm willing to also port the PCL part of NTS to .NET Core if this done.

**Comment by DGuidi** [comment]
@xivk nope. and sincerely I haven't time to work on it soon :(

**Comment by xivk** [comment]
I can also provide a build server for NTS and all it's projects that **will** work if that helps? I have a TeamCity instance running I could use... It's been continuously use for a couple of years and I update it regularly for my own builds so now worries about stability.

I depend on these projects for my day to day work and I need them converted so it's not acceptable to have to wait for travis to adjust their service for .NET core.

**Comment by DGuidi** [comment]
you can point your build server to your branches, or try to fix also travis build. probably isn't a big issue, I thought

**Comment by xivk** [comment]
I found [this](http://andrewlock.net/adding-travis-ci-to-a-net-core-app/) but it's for .NET core **only** if i'm not mistaken. Not sure how to proceed on this. I don't have a lot of time right now, I can check in a couple of days.

**Comment by xivk** [comment]
Just to be clear, the build server is there just to check if the code builds right? I don't see any testing...? 

Does this mean it's OK if I add a custom build.sh script that builds the .NET projects with mono and the .NET core projects with the new dotnet tooling?

**Comment by DGuidi** [comment]
build failed so no tests are run. for a successful build, all tests are executed, too:
see [here](https://travis-ci.org/NetTopologySuite/NetTopologySuite/builds/149109816) from line 6000

**Comment by xivk** [comment]
Ok, build is fixed by:

- Adding a custom build script.
- Have travis install mono and dotnet core.
- Adding a platform CIBuild that is used for the mono build to build the .NET and PCL projects.
- Adding a build script that only builds the dotnet core project GeoAPI.NetCore.

If this is ok for everybody we can merge.

**Comment by DGuidi** [comment]
thanks for this :)

**Comment by DGuidi** [comment]
I plan to move actual code fron GeoApi.Core to plain 'GeoApi'

**Pull request merged**
